### PR TITLE
I added CSS theming 

### PR DESCRIPTION
**Pull request by hinzwifi**
It saves the theme into the browser

### CODE REVIEW

**Comment by jakedolan443** [comment]
Nice work, though I noticed the datatables remained their initial colour - this theming mechanism merely changes the background colour of the page. If possible, try to change the datatable colour, I followed [this guide](https://datatables.net/forums/discussion/36595/change-the-row-color-based-on-column-data) but had no luck.

**Comment by hinzwifi** [comment]
Okay2 I'll look into that guide you provided and add it and also by the way I can't seem to have any data. Do you have any solution for it?
image

**Comment by jakedolan443** [comment]
You likely overflooded the API and your requests will be dropped for sometime, you will probably see an API error in the log. You have two options - [You can use an API key](https://support.kraken.com/hc/en-us/articles/360022839451-Generate-API-keys), or, you can use existing data by directly inserting the cache.

 
In the function `fetch_new_data()` in `server.py`

Replace the line `coins = self.read_coins_file()` with:
```
coins = []
```
Replace the line `self.__cache = ls.copy()` with:
```
self.cache = [{'img': 'icons/algo.png', 'price': '$ 1.26', 'change_colour': 'green', 'change': '+3.99%', 'code': 'ALGO', 'name': 'Algorand'}, {'img': 'icons/ada.png', 'price': '$ 2.87', 'change_colour': 'red', 'change': '-2.49%', 'code': 'ADA', 'name': 'Cardano'}, {'img': 'icons/dash.png', 'price': '$ 254.07', 'change_colour': 'green', 'change': '+0.63%', 'code': 'DASH', 'name': 'Dash'}, {'img': 'icons/keep.png', 'price': '$ 0.47', 'change_colour': 'green', 'change': '+1.33%', 'code': 'KEEP', 'name': 'Keep Network'}, {'img': 'icons/xmr.png', 'price': '$ 305.11', 'change_colour': 'red', 'change': '-1.76%', 'code': 'XMR', 'name': 'Monero'}, {'img': 'icons/ocean.png', 'price': '$ 0.95', 'change_colour': 'green', 'change': '+2.40%', 'code': 'OCEAN', 'name': 'Ocean'}, {'img': 'icons/sc.png', 'price': '$ 0.02', 'change_colour': 'green', 'change': '+8.65%', 'code': 'SC', 'name': 'Siacoin'}, {'img': 'icons/trx.png', 'price': '$ 0.10', 'change_colour': 'red', 'change': '-0.25%', 'code': 'TRX', 'name': 'Tron'}, {'img': 'icons/zec.png', 'price': '$ 163.60', 'change_colour': 'green', 'change': '+1.57%', 'code': 'ZEC', 'name': 'Zcash'}]
```

This stops the server from using API data and instead uses the cache supplied above. Make sure to revert this change before commits

**Comment by hinzwifi** [comment]
Ohhh okay2 thank you will do.  I wanna do a sanity check before I do my things is that do you want the data tables to have dark and light mode or change the color(red or green) depending on the data.

**Comment by jakedolan443** [comment]
Here is a rough template for what I have in mind:

Of course, if you have any ideas/changes, feel free to implement them, I'm sure my design skills are lacking compared to masses, this is just a template. 
If I understand CSS correctly, this would also be in the form of
```
.theme_1 {
  background-color: x
  more-stuff: x
}
```
If implemented correctly, this would mean new themes could be selected with ease, via a select button, e.g.

Where each selection would trigger a different CSS theme.

**Pull request closed without merging**
